'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Interfacer5.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Safe Handling Advice.
        '''</summary>
        Friend ReadOnly Property Advice_on_safe_handling() As String
            Get
                Return ResourceManager.GetString("Advice_on_safe_handling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Appearance.
        '''</summary>
        Friend ReadOnly Property Appearance() As String
            Get
                Return ResourceManager.GetString("Appearance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Autoignition Temperature.
        '''</summary>
        Friend ReadOnly Property Autoignition_temperature() As String
            Get
                Return ResourceManager.GetString("Autoignition_temperature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bioaccumulative Potential.
        '''</summary>
        Friend ReadOnly Property Bioaccumulative_potential() As String
            Get
                Return ResourceManager.GetString("Bioaccumulative_potential", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Boiling Point.
        '''</summary>
        Friend ReadOnly Property Boiling_point() As String
            Get
                Return ResourceManager.GetString("Boiling_point", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carcinogenicity.
        '''</summary>
        Friend ReadOnly Property Carcinogenicity() As String
            Get
                Return ResourceManager.GetString("Carcinogenicity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chemical Stability.
        '''</summary>
        Friend ReadOnly Property Chemical_stability() As String
            Get
                Return ResourceManager.GetString("Chemical_stability", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chronic.
        '''</summary>
        Friend ReadOnly Property Chronic() As String
            Get
                Return ResourceManager.GetString("Chronic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conditions to Avoid.
        '''</summary>
        Friend ReadOnly Property Conditions_to_avoid() As String
            Get
                Return ResourceManager.GetString("Conditions_to_avoid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contains.
        '''</summary>
        Friend ReadOnly Property Contains() As String
            Get
                Return ResourceManager.GetString("Contains", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Decomposition Temperature.
        '''</summary>
        Friend ReadOnly Property Decomposition_temperature() As String
            Get
                Return ResourceManager.GetString("Decomposition_temperature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disposal.
        '''</summary>
        Friend ReadOnly Property Disposal() As String
            Get
                Return ResourceManager.GetString("Disposal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to US Department of Transportation.
        '''</summary>
        Friend ReadOnly Property DOT() As String
            Get
                Return ResourceManager.GetString("DOT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transport Label.
        '''</summary>
        Friend ReadOnly Property DOT_label() As String
            Get
                Return ResourceManager.GetString("DOT_label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Embryotoxicity.
        '''</summary>
        Friend ReadOnly Property Embryotoxicity() As String
            Get
                Return ResourceManager.GetString("Embryotoxicity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Engineering Controls.
        '''</summary>
        Friend ReadOnly Property Engineering_controls() As String
            Get
                Return ResourceManager.GetString("Engineering_controls", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EPA Registration.
        '''</summary>
        Friend ReadOnly Property EPA_number() As String
            Get
                Return ResourceManager.GetString("EPA_number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Evaporation Rate.
        '''</summary>
        Friend ReadOnly Property Evaporation_rate() As String
            Get
                Return ResourceManager.GetString("Evaporation_rate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explosive Limits.
        '''</summary>
        Friend ReadOnly Property Explosive_limits() As String
            Get
                Return ResourceManager.GetString("Explosive_limits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eye.
        '''</summary>
        Friend ReadOnly Property Eye_contact() As String
            Get
                Return ResourceManager.GetString("Eye_contact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eye/Face Protection.
        '''</summary>
        Friend ReadOnly Property Eye_face_protection() As String
            Get
                Return ResourceManager.GetString("Eye_face_protection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eye Contact.
        '''</summary>
        Friend ReadOnly Property FA_eye_contact() As String
            Get
                Return ResourceManager.GetString("FA_eye_contact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ingestion.
        '''</summary>
        Friend ReadOnly Property FA_ingestion() As String
            Get
                Return ResourceManager.GetString("FA_ingestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inhalation.
        '''</summary>
        Friend ReadOnly Property FA_inhalation() As String
            Get
                Return ResourceManager.GetString("FA_inhalation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skin Contact.
        '''</summary>
        Friend ReadOnly Property FA_skin_contact() As String
            Get
                Return ResourceManager.GetString("FA_skin_contact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash Point.
        '''</summary>
        Friend ReadOnly Property Flash_point() As String
            Get
                Return ResourceManager.GetString("Flash_point", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Freezing Point.
        '''</summary>
        Friend ReadOnly Property Freezing_point() As String
            Get
                Return ResourceManager.GetString("Freezing_point", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to General Hygiene Considerations.
        '''</summary>
        Friend ReadOnly Property General_hygiene_considerations() As String
            Get
                Return ResourceManager.GetString("General_hygiene_considerations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hazard Classification.
        '''</summary>
        Friend ReadOnly Property Hazard_classification() As String
            Get
                Return ResourceManager.GetString("Hazard_classification", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OSHA Hazard Status.
        '''</summary>
        Friend ReadOnly Property Hazard_classification1() As String
            Get
                Return ResourceManager.GetString("Hazard_classification1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hazard Statements.
        '''</summary>
        Friend ReadOnly Property Hazard_statement() As String
            Get
                Return ResourceManager.GetString("Hazard_statement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hazardous Combustion Products.
        '''</summary>
        Friend ReadOnly Property Hazardous_combustion_products() As String
            Get
                Return ResourceManager.GetString("Hazardous_combustion_products", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Decomposition Hazards.
        '''</summary>
        Friend ReadOnly Property Hazardous_decomposition_products() As String
            Get
                Return ResourceManager.GetString("Hazardous_decomposition_products", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hazardous Polymerization.
        '''</summary>
        Friend ReadOnly Property Hazardous_polymerization() As String
            Get
                Return ResourceManager.GetString("Hazardous_polymerization", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incompatibilities.
        '''</summary>
        Friend ReadOnly Property Incompatibilities() As String
            Get
                Return ResourceManager.GetString("Incompatibilities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ingestion.
        '''</summary>
        Friend ReadOnly Property Ingestion() As String
            Get
                Return ResourceManager.GetString("Ingestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inhalation.
        '''</summary>
        Friend ReadOnly Property Inhalation() As String
            Get
                Return ResourceManager.GetString("Inhalation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Large Spill Clean-up.
        '''</summary>
        Friend ReadOnly Property Large_spills() As String
            Get
                Return ResourceManager.GetString("Large_spills", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exposure Routes.
        '''</summary>
        Friend ReadOnly Property Likely_routes_of_exposure() As String
            Get
                Return ResourceManager.GetString("Likely_routes_of_exposure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mobility.
        '''</summary>
        Friend ReadOnly Property Mobility() As String
            Get
                Return ResourceManager.GetString("Mobility", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mutagenicity.
        '''</summary>
        Friend ReadOnly Property Mutagenicity() As String
            Get
                Return ResourceManager.GetString("Mutagenicity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Note to Health Care Provider.
        '''</summary>
        Friend ReadOnly Property Note_to_HCP() As String
            Get
                Return ResourceManager.GetString("Note_to_HCP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Odor.
        '''</summary>
        Friend ReadOnly Property Odor() As String
            Get
                Return ResourceManager.GetString("Odor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Odor Threshold.
        '''</summary>
        Friend ReadOnly Property Odor_threshold() As String
            Get
                Return ResourceManager.GetString("Odor_threshold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Packing Group.
        '''</summary>
        Friend ReadOnly Property Packing_group() As String
            Get
                Return ResourceManager.GetString("Packing_group", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partition Coefficient.
        '''</summary>
        Friend ReadOnly Property Partition_coefficient() As String
            Get
                Return ResourceManager.GetString("Partition_coefficient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Persistence.
        '''</summary>
        Friend ReadOnly Property Persistence() As String
            Get
                Return ResourceManager.GetString("Persistence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Personal Precautions.
        '''</summary>
        Friend ReadOnly Property Personal_precautions() As String
            Get
                Return ResourceManager.GetString("Personal_precautions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to pH.
        '''</summary>
        Friend ReadOnly Property pH() As String
            Get
                Return ResourceManager.GetString("pH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disposal.
        '''</summary>
        Friend ReadOnly Property Pre_disposal() As String
            Get
                Return ResourceManager.GetString("Pre_disposal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prevention.
        '''</summary>
        Friend ReadOnly Property Pre_prevention() As String
            Get
                Return ResourceManager.GetString("Pre_prevention", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Response.
        '''</summary>
        Friend ReadOnly Property Pre_response() As String
            Get
                Return ResourceManager.GetString("Pre_response", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Storage.
        '''</summary>
        Friend ReadOnly Property Pre_storage() As String
            Get
                Return ResourceManager.GetString("Pre_storage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Precautions for Fire-Fighters.
        '''</summary>
        Friend ReadOnly Property Precautions_for_firefighters() As String
            Get
                Return ResourceManager.GetString("Precautions_for_firefighters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Primary Hazard.
        '''</summary>
        Friend ReadOnly Property Primary_haz() As String
            Get
                Return ResourceManager.GetString("Primary_haz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product Class.
        '''</summary>
        Friend ReadOnly Property Product_class() As String
            Get
                Return ResourceManager.GetString("Product_class", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend ReadOnly Property Product_description() As String
            Get
                Return ResourceManager.GetString("Product_description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Product Name.
        '''</summary>
        Friend ReadOnly Property Product_name() As String
            Get
                Return ResourceManager.GetString("Product_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proper Shipping Name.
        '''</summary>
        Friend ReadOnly Property Proper_shipping_name() As String
            Get
                Return ResourceManager.GetString("Proper_shipping_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RCRA Status.
        '''</summary>
        Friend ReadOnly Property RCRA_status() As String
            Get
                Return ResourceManager.GetString("RCRA_status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reproductive Effects.
        '''</summary>
        Friend ReadOnly Property Reproductive_effects() As String
            Get
                Return ResourceManager.GetString("Reproductive_effects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Respiratory Protection.
        '''</summary>
        Friend ReadOnly Property Respiratory_protection() As String
            Get
                Return ResourceManager.GetString("Respiratory_protection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Secondary Hazard.
        '''</summary>
        Friend ReadOnly Property Secondary_haz() As String
            Get
                Return ResourceManager.GetString("Secondary_haz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hypersensitivity.
        '''</summary>
        Friend ReadOnly Property Sensitization_to_product() As String
            Get
                Return ResourceManager.GetString("Sensitization_to_product", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Signal Word.
        '''</summary>
        Friend ReadOnly Property Signal_word() As String
            Get
                Return ResourceManager.GetString("Signal_word", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skin.
        '''</summary>
        Friend ReadOnly Property Skin_contact() As String
            Get
                Return ResourceManager.GetString("Skin_contact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skin Protection.
        '''</summary>
        Friend ReadOnly Property Skin_protection() As String
            Get
                Return ResourceManager.GetString("Skin_protection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Small Spill Clean-up.
        '''</summary>
        Friend ReadOnly Property Small_spills() As String
            Get
                Return ResourceManager.GetString("Small_spills", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Solubility.
        '''</summary>
        Friend ReadOnly Property Solubility() As String
            Get
                Return ResourceManager.GetString("Solubility", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specific Gravity.
        '''</summary>
        Friend ReadOnly Property Specific_gravity() As String
            Get
                Return ResourceManager.GetString("Specific_gravity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specific Hazards.
        '''</summary>
        Friend ReadOnly Property Specific_hazards() As String
            Get
                Return ResourceManager.GetString("Specific_hazards", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Storage Conditions.
        '''</summary>
        Friend ReadOnly Property Storage_conditions() As String
            Get
                Return ResourceManager.GetString("Storage_conditions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DisposalConsiderations.
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suitable Extinguishing Media.
        '''</summary>
        Friend ReadOnly Property Suitable_extinguishing_media() As String
            Get
                Return ResourceManager.GetString("Suitable_extinguishing_media", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suitable Materials.
        '''</summary>
        Friend ReadOnly Property Suitable_materials_of_construction() As String
            Get
                Return ResourceManager.GetString("Suitable_materials_of_construction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier.
        '''</summary>
        Friend ReadOnly Property Supplier() As String
            Get
                Return ResourceManager.GetString("Supplier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier Address.
        '''</summary>
        Friend ReadOnly Property Supplier_address() As String
            Get
                Return ResourceManager.GetString("Supplier_address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emergency Contact.
        '''</summary>
        Friend ReadOnly Property Supplier_ec() As String
            Get
                Return ResourceManager.GetString("Supplier_ec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier Phone.
        '''</summary>
        Friend ReadOnly Property Supplier_phone() As String
            Get
                Return ResourceManager.GetString("Supplier_phone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Syngergistic Products.
        '''</summary>
        Friend ReadOnly Property Synergistic_products() As String
            Get
                Return ResourceManager.GetString("Synergistic_products", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Teratogenicity.
        '''</summary>
        Friend ReadOnly Property Teratogenicity() As String
            Get
                Return ResourceManager.GetString("Teratogenicity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property tnccIcon256() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("tnccIcon256", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TSCA.
        '''</summary>
        Friend ReadOnly Property TSCA() As String
            Get
                Return ResourceManager.GetString("TSCA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UN Number.
        '''</summary>
        Friend ReadOnly Property UN_number() As String
            Get
                Return ResourceManager.GetString("UN_number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unsuitable Extinguishing Media.
        '''</summary>
        Friend ReadOnly Property Unsuitable_extinguishing_media() As String
            Get
                Return ResourceManager.GetString("Unsuitable_extinguishing_media", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unsuitable Materials.
        '''</summary>
        Friend ReadOnly Property Unsuitable_materials_of_construction() As String
            Get
                Return ResourceManager.GetString("Unsuitable_materials_of_construction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Density.
        '''</summary>
        Friend ReadOnly Property Vapor_density() As String
            Get
                Return ResourceManager.GetString("Vapor_density", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vapor Pressure.
        '''</summary>
        Friend ReadOnly Property Vapor_pressure() As String
            Get
                Return ResourceManager.GetString("Vapor_pressure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Viscosity.
        '''</summary>
        Friend ReadOnly Property Viscosity() As String
            Get
                Return ResourceManager.GetString("Viscosity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VOC Content.
        '''</summary>
        Friend ReadOnly Property VOC_content() As String
            Get
                Return ResourceManager.GetString("VOC_content", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
